server:
  port: ${PORT:8000}
spring:
  application:
    name: user-api
  datasource:
    url: jdbc:h2:mem:user-api
    username: sa
    password:
  h2:
    console:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
